"""Initial migration

Revision ID: 1fd9907454a4
Revises: 
Create Date: 2026-02-11 14:21:06.500861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd9907454a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('owner_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reindeer',
    sa.Column('reindeer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.String(length=20), nullable=True),
    sa.Column('mother_owner_id', sa.String(length=20), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('mother_id', sa.String(length=12), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('life_slaughter', sa.Boolean(), nullable=True),
    sa.Column('vaja', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.owner_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('reindeer_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reindeer_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['reindeer_id'], ['reindeer.reindeer_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('reindeer_events',
    sa.Column('reindeer_event_id', sa.Integer(), nullable=False),
    sa.Column('reindeer_id', sa.Integer(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('event_season', sa.String(length=64), nullable=True),
    sa.Column('modified_date', sa.Date(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('life_slaughter', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['reindeer_id'], ['reindeer.reindeer_id'], ),
    sa.PrimaryKeyConstraint('reindeer_event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reindeer_events')
    op.drop_table('comments')
    op.drop_table('reindeer')
    op.drop_table('user')
    op.drop_table('owner')
    # ### end Alembic commands ###
