"""Add password hashing and ear_tags

Revision ID: b6ab79f8aa4f
Revises: 1fd9907454a4
Create Date: 2026-02-11 14:49:04.925754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6ab79f8aa4f'
down_revision = '1fd9907454a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reindeer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ear_tag', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('mother_ear_tag', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['ear_tag'])
        batch_op.drop_column('mother_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('reindeer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mother_id', mysql.VARCHAR(length=12), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('mother_ear_tag')
        batch_op.drop_column('ear_tag')

    # ### end Alembic commands ###
